// Auto-generated by generate-css-variables.cjs
export const themes = [
  {
    "name": "dive-theme",
    "modes": [
      "dark-mode",
      "hc-dark-mode",
      "hc-light-mode",
      "light-mode"
    ],
    "css": "src/tokens/css-vars/dive-theme/index.css"
  }
];
